config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'sessions#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  resources :cards
  resources :decks do
    get :search, to: 'decks#search'
  end
  resources :users
  resources :decklists, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :decklists, dependent: :destroy
  has_many :cards, through: :decklists
  belongs_to :user




end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :correct_user, only: :destroy

  def index
    @decks = Deck.paginate(page: params[:page])
  end

  def show
    @deck       = Deck.find(params[:id])
    @agendas    = @deck.cards.where(card_type: "Agenda").order(:name => :asc)
    @havens     = @deck.cards.where(card_type: "Haven").order(:name => :asc)
    @characters = @deck.cards.where(card_type: "Character").order(:name => :asc)
    @attacks    = @deck.cards.where("card_type LIKE ? OR card_type LIKE ?", "%Attack%", "%Defense%").order(:name => :asc)
    @actions    = @deck.cards.where("card_type LIKE ?", "%Action%").order(:name => :asc)
    @library    = @deck.cards.where.not(card_type: ["Agenda", "Haven", "Character"]).length
    @cards      = Card.all.where(card_type: "Haven").order(:name => :asc)
    @notes      = @deck.notes
    if @deck.leader
      @leader     = Card.find(@deck.leader)
    end
  end

  def new
    redirect_to root_path
  end

  def create
    user = User.find(params[:id])
    @deck = user.decks.new(deck_params)
    if @deck.save
      @cards = Card.all
      redirect_to @deck
    else
      redirect_to root_path
    end
  end

  def update
    @deck = Deck.find(params[:id])
    @deck.update(deck_params)
    redirect_to @deck
  end

  def edit
    @deck = Deck.find(params[:id])
    @card = Card.find(params[:c_id])
    list = @deck.decklists.find_by(card_id: params[:c_id])
    if list
      list.delete
      respond_to do |format|
        format.js
        format.html { redirect_to @deck }
      end
    end
  end

  def search
    @deck = Deck.find(params[:d_id])
    @cards = Card.search(params[:name],
                         params[:faction],
                         params[:card_type],
                         params[:blood_requirement],
                         params[:blood],
                         params[:physical],
                         params[:social],
                         params[:mental],
                         params[:tags],
                         params[:attack_type],
                         params[:disciplines],
                         params[:text],
                         params[:product],
                       ).order(:name => :asc)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def destroy
    @deck.destroy
    flash[:success] = "Deck deleted"
    redirect_to @deck.user
  end

  private
    def deck_params
      params.require(:deck).permit(:name, :public, :leader, :notes)
    end

    def correct_user
      @deck = current_user.decks.find_by(id: params[:id])
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_button.html.erb
<%# buttons for adding/removing cards from deck %>
<%= button_to "0", decklists_path,
                     params: {c_id: card.id, d_id: id, val: 0},
                     remote: true,
                     class: " sm-btn qty" %>
<%= button_to "1", decklists_path,
                     params: {c_id: card.id, d_id: id, val: 1},
                     remote: true,
                     class: " sm-btn qty" %>

<%# only add last buttons if they can be legally added %>
<% unless card.card_type === "Haven" || card.card_type === "Agenda" || card.card_type === "Character" %>

<%= button_to "2", decklists_path,
                     params: {c_id: card.id, d_id: id, val: 2},
                     remote: true,
                     class: " sm-btn qty" %>
<%= button_to "3", decklists_path,
                     params: {c_id: card.id, d_id: id, val: 3},
                     remote: true,
                     class: " sm-btn qty" %>
<% end %>

app/views/decks/_card.html.erb
<!-- cards in search area, not decklist -->
<div class="row card-row text-center">
  <!-- render row of card information for deck page -->

  <div class="col-lg-1 col-md-2 col-sm-2 col-xs-3">
    <div class="row buttons">
      <!-- add/remove buttons -->
      <%= render 'decks/button', card: card, id: id %>
    </div>
  </div>

  <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4 text-left">
    <!-- card name -->
    <%= link_to card.name, card, remote: true%>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
    <%# clan symbol %>
    <% if card.faction && card.faction != "Neutral" %>
      <%= image_tag card.faction %>
    <% else %>
      -
    <% end %>
  </div>

  <div class="col-lg-1 col-md-1 col-sm-1 hidden-xs">
    <!-- blood -->
    <%= card.blood %>
    <%= card.blood_requirement %>
  </div>
  <div class="col-lg-2 hidden-md hidden-sm hidden-xs">
    <%# character stats %>
    <% if card.card_type === "Character" %>
      <%= card.physical %>/
      <%= card.social %>/
      <%= card.mental %>
    <% else %>
      -
    <% end %>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3">
    <!-- attack/defense stats -->
    <% if card.card_type.include? "Attack" %>
      <%= render 'shared/renderIcon', types: card.attack_type.split(",") %>
    <% end %>

    <% if card.card_type.include? "Defense" %>
      <%= render 'shared/renderIcon', types: card.reaction_type.split(",") %>
    <% end %>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-2 hidden-xs">
    <!-- damage/shield -->
    <%= card.damage %>
    <%= card.shield %>
  </div>

  <%# factor out div? only needed on first load %>
  <div class="qty-in-deck hidden">
    <%= count %>
  </div>
</div>

app/views/decks/_cardGroup.html.erb
<div id=<%= id %>>
  <div class="row">
    <h4><%= title %> (<span id="<%= type %>-count"><%= cards.length %></span>)</h4>
  </div>
  <div class="card-container row">
    <% cards.uniq.each do |card| %>
      <%= render 'decks/deckCard', card: card, card_count: cards.where(name: card.name).length %>
    <% end %>
  </div>
</div>

app/views/decks/_categories.html.erb
<div class="centered">
  <!-- split deck list by card type -->
  <div class="row centered">

    <div class="col-md-6 col-sm-6 col-xs-6">
      <%= render 'decks/category', cards: @agendas, type: "agenda", title: "Agenda" %>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-6">
      <%= render 'decks/category', cards: @havens, type: "haven", title: "Haven" %>
    </div>

  </div>

  <div class="row centered">

    <div class="col-md-12 col-sm-12 col-xs-12">
      <%= render 'decks/characters',
          cards: @characters,  #send character cards
          type: "character",   #dynamic div id
          title: "Characters", #row header
          leader: @leader,     #single out leader card
          deck: @deck          #send deck info
      %>
    </div>

  </div>

  <div class="row centered">

    <h3>Library (<span id="library-count"><%= @library %></span>)</h3>

    <div class="col-md-6 col-sm-6 col-xs-12 centered">
      <%= render 'category', cards: @attacks, type: "attack", title: "Attacks/Reactions" %>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-12 centered">
      <%= render 'category', cards: @actions, type: "action", title: "Action" %>
    </div>

  </div>

</div>

app/views/decks/_category.html.erb
<div id=<%= type %>>
  <div class="row">
    <h4><%= title %> (<span id="<%= type %>-count"><%= cards.length %></span>)</h4>
  </div>
  <div class="card-container row">
    <% cards.uniq.each do |card| %>
    <!-- render each card with count -->
      <%= render 'decks/deckCard',
        card: card,
        card_count: cards.where(name: card.name).length %>
    <% end %>
  </div>
</div>

app/views/decks/_character.html.erb
<div id="c_<%= card.id %>" class="row">
  <div class="count hidden">
    <%= card_count %>
  </div>
  <div class="col-md-5 col-sm-2 col-xs-5 white-link">
    <!-- render character card -->
    <%= link_to card.name, card, remote: true %>
    <!-- check if character is leader -->
    <% if leader %>
      - Leader
    <% end %>
  </div>
  <% if current_user?(@deck.user) %>
    <% unless leader %>
    <!-- form to make character leader -->
      <div class="col-md-1 col-xs-2">
        <%= form_with model: deck do |f| %>
          <%= f.hidden_field :leader, value: card.id %>
          <%= f.submit "^", class:"btn-round" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/decks/_characters.html.erb
<div id=<%= type %>>
  <div class="row">
    <h4><%= title %> (<span id="<%= type %>-count"><%= cards.length %></span>)</h4>
  </div>

  <!-- render leader character first -->
  <% if leader %>
    <div class="row">
      <%= render 'character',
        card: leader,
        card_count: cards.where(name: leader.name).length,
        leader: true
      %>
    </div>
  <% end %>
  <div class="card-container row">
    <!-- render all other characters -->
    <% cards.uniq.each do |card| %>
      <% unless card === leader %>
        <%= render 'character',
          card: card,
          card_count: cards.where(name: card.name).length,
          deck: @deck,
          leader: false
        %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/decks/_deckCard.html.erb
<!-- card in decklist, not search area -->
<div id="c_<%= card.id %>" class="row">
  <% if card.card_type === "Agenda" || card.card_type === "Haven" %>
    <div class="count hidden">
      <%= card_count %>
    </div>
    <div class="col-xs-12 white-link">
      <%= link_to card.name, card, remote: true %>
    </div>
  <% else %>
    <div class="col-md-1 col-xs-1 count">
      <%= card_count %>
    </div>
    <div class="col-md-6 col-xs-10 padding-0 white-link">
      <%= link_to card.name, card, remote: true %>
    </div>
  <% end %>
</div>

app/views/decks/_deckInfo.html.erb
<div class="deck-info">
  <!-- render deck options for owner only -->
  <% if current_user?(@deck.user) %>
    <%= render 'decks/nameForm', deck: @deck %>
  <% end %>
</div>

app/views/decks/_listHeader.html.erb
<div class="row text-center list-header">

  <div class="col-lg-1 col-md-2 col-sm-2 col-xs-3 text-left">
    Qty.
  </div>

  <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4 text-left">
    Name
  </div>

  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 ">
    Clan
  </div>

  <div class="col-lg-1 col-md-1 col-sm-1 hidden-xs">
    <%= image_tag 'blood_potency' %>
  </div>

  <div class="col-lg-2 hidden-md hidden-sm hidden-xs">
    <%= image_tag 'Physical' %>/
    <%= image_tag 'Social' %>/
    <%= image_tag 'Mental' %>
  </div>

  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3">
    Att/React
  </div>

  <div class="col-lg-2 col-md-2 col-sm-2 hidden-xs">
    <%= image_tag 'Damage' %>/<%= image_tag 'Shield' %>
  </div>

</div>

app/views/decks/edit.js.erb
var element = document.querySelector("#c_<%= j @card.id %> > .count");
var count = parseInt(element.innerHTML);
var type = "<%= j @card.card_type %>".toLowerCase();
var first_type = type.replace(/,.*/, '');

/* Decrement/remove card count */
if (count > 1){
  element.innerHTML = count - 1
}
else if (element){
  $("#c_<%= j @card.id %>").remove()
}
else {
  alert("You found an error! Let Ryan know how you broke his site!")
}
/* Decrement main counter */
if (count > 0) {
  if (type.includes("attack") || type.includes("defense")) {
    var counter = $("#attack-count")
    var i = parseInt(counter.html())
    counter.html(i - 1);
  }
  else {
    var counter = $(`#${first_type}-count`)
    var i = parseInt(counter.html())
    counter.html(i - 1);
  }
}
if (type != "character" && type != "aganda" && type != "haven") {
  var counter = $(`#library-count`)
  var i = parseInt(counter.html())
  counter.html(i - 1);
}

app/views/decks/index.html.erb
<% provide(:title, 'Recent Decks') %>
<div class="container">
  <div class="row white offset bold p-20">
    <h1>Published decklists</h1>
  </div>

  <div class="paginate">
    <%= will_paginate if @decks.length > 30 %>
  </div>

    <div class="card-list max-800">
      <% @decks.each do |deck| %>
        <% if deck.public %>
          <%= link_to deck do %>
            <%= render 'users/deckRow', deck: deck %>
          <% end %>
        <% end%>
      <% end %>
    </div>

    <div class="paginate">
      <%= will_paginate if @decks.length > 30 %>
    </div>

</div>

app/views/decks/search.js.erb
var results = $(".results")
results.empty()

<% @cards.each do |card| %>
  var count = "<%= @deck.cards.where(name: card.name).length %>";
  // factor out count? only needed on first load
  results.append(`<%= escape_javascript(render 'decks/card', card: card, id: @deck.id, count: @deck.cards.where(id: card.id).length) %>`)
  $(".card-row").last().find(".qty:eq("+ count + ")").addClass('active')
<% end %>
$("#search-form").trigger("reset")

app/views/decks/show.html.erb
<% provide(:title, @deck.name) %>
<%# Set page as one row of two columns %>
<div class="container">
  <div class="row deck-main">
    <div class="card-pic">
      <!-- Display card images -->
    </div>
    <div class="col-md-4 col-sm-12 col-xs-12">
       <!-- placeholder for fixed content -->
    </div>
    <!-- Fix decklist to left side of screen  -->
    <div class="col-md-4 col-sm-12 col-xs-12 left scrollable white">
      <div class="hidden-lg hidden-md">
        <%= image_tag 'vtmBannerTrans', class: "dynamic-img" %>
      </div>
      <div class="inner-content">
        <div class="">
          <% if !@deck.name.empty? %>
            <h1><%= @deck.name %></h1>
          <% else %>
            <h1><%= @deck.user.username %>'s deck</h1>
          <% end %>
        </div>

        <% if current_user?(@deck.user) %>
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home">Decklist</a></li>
            <li><a data-toggle="tab" href="#menu1">Notes</a></li>
            <li><a data-toggle="tab" href="#menu2">Edit info</a></li>
          </ul>
        <% end %>

        <div class="tab-content">

          <div id="home" class="tab-pane fade in active">
            <% if current_user?(@deck.user) %>
              <div class="white small m-10">
                Changes to deck saved automatically
              </div>
              <div class="white small m-10">
                <button class="btn-round">^</button> - Make character Leader
              </div>
            <% end %>

            <%= render 'categories' %>

          </div>

          <div id="menu1" class="tab-pane fade">
            <% if current_user?(@deck.user) %>
              <div class="inner-form" %>
                <h4 class="white">Description</h4>
                  <%= form_with model: @deck do |f| %>
                    <%= f.text_area :notes, placeholder: @notes %>
                    <%= f. submit "Save Notes", class:"m-10 lg-btn" %>
                  <% end %>
              </div>
            <% end %>
          </div>

          <div id="menu2" class="tab-pane fade">
            <%= render 'deckInfo' %>
          </div>

        </div>
      </div>
    </div>

    <div class="col-md-8 col-xs-12 centered right">
      <div class="hidden-sm hidden-xs">
        <%= image_tag 'vtmBannerTrans', class: "dynamic-img" %>
      </div>

      <% if current_user?(@deck.user) %>

      <!-- Card search on right side -->
      <div class="search-bar split-form">
        <!-- render search form with appropriate url path -->
        <%= form_with url: 'decks/search', method: :get, id: "search-form", local: false do |f| %>
          <%= hidden_field_tag :d_id, @deck.id %>
          <%= render 'shared/search', :f => f %>
        <% end %>
      </div>
      <!-- Card list on right side -->
      <div class="centered list">
        <div class="card-list">
          <%= render 'listHeader' %>
          <div class="results">
            <% @cards.each do |card| %>
              <%= render 'card', id: @deck.id, card:card, count: @deck.cards.where(id: card.id).length %>
            <% end %>
          </div>
        </div>
      </div>

      <% else %>

      <div class="description-area">
        <h1>Notes from <%= @deck.user.username %></h1>
          <%= simple_format(@notes) %>
      </div>

      <% end %>
    </div>
  </div>
</div>