config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'sessions#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  resources :cards
  resources :decks do
    get :search, to: 'decks#search'
  end
  resources :users
  resources :decklists, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('Brujah') %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="">
    <%= render 'layouts/nav' %>
  </div>
</header>

app/views/layouts/_nav.html.erb
<nav>
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#header-navbar-collapse-1"
            aria-expanded="false" >
      <span class="sr-only">Toggle navigaton</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <ul class= "nav navbar-nav navbar-right collapse navbar-collapse"
      id="header-navbar-collapse-1">
      <li> <%= link_to "Card Search", cards_path %></li>
      <li> <%= link_to "Decklists",   decks_path %></li>

    <% if logged_in? %>
      <li class= "dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark">
          <li><%= link_to "My Decks", current_user %></li>
          <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li> <%= link_to "Log In",  login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/header' %>

    <div class="content">
      <% flash.each do |type, msg| %>
        <div>
          <div class="alert alert-<%= type %>"><%= msg %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%# <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>